version: '3.8'

services:
  web:
    build: .
    container_name: web
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file: .env
    depends_on:
      - db

  db:
    image: postgres
    container_name: db
    env_file: .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    restart: always
    env_file: .env
    ports:
      - "5050:80"

volumes:
  postgres_data:
